services:
  - type: web
    name: karibo
    env: go
    plan: free
    autoDeploy: true

    buildCommand: |
      go build -o main .

    startCommand: ./main

    envVars:
      - key: PORT
        value: 10000
