services:
  - type: web
    name: karibo
    env: go
    buildCommand: GOSUMDB=off go build -o main .
    startCommand: ./main
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: GOSUMDB
        value: off
